// ============================================================
// TRIP EXPORT — PDF (browser print) + ICS calendar
// No external deps. PDF uses browser print, ICS is hand-rolled.
// ============================================================

import type { Trip, Reservation, TransportLeg } from '@barry/shared-types';

interface ExportContext {
  trip: Trip;
  reservations?: Reservation[];
  transportLegs?: TransportLeg[];
  totalCost?: number;
}

// ============================================================
// ICS CALENDAR — RFC 5545
// ============================================================

function pad2(n: number) { return n < 10 ? `0${n}` : `${n}`; }

/** Format a Date as YYYYMMDDTHHmmssZ (UTC). */
function toIcsDateTime(d: Date): string {
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}T${pad2(d.getUTCHours())}${pad2(d.getUTCMinutes())}${pad2(d.getUTCSeconds())}Z`;
}

/** Format a Date as YYYYMMDD (date only). */
function toIcsDate(d: Date): string {
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}`;
}

/** Escape a value for ICS (commas, semicolons, newlines). */
function escIcs(s: string): string {
  return (s || '')
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
}

export function buildIcs(ctx: ExportContext): string {
  const { trip } = ctx;
  const now = toIcsDateTime(new Date());
  const isTrip = trip.mode === 'trip';
  const start = trip.scheduledAt ? new Date(trip.scheduledAt) : null;
  const end = trip.endDate ? new Date(trip.endDate) : null;

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Barry//Trip Export//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  if (start) {
    lines.push('BEGIN:VEVENT');
    lines.push(`UID:${trip.id}@barry.app`);
    lines.push(`DTSTAMP:${now}`);

    if (isTrip && end) {
      // Multi-day event — DATE values
      lines.push(`DTSTART;VALUE=DATE:${toIcsDate(start)}`);
      // ICS DTEND is exclusive for all-day, so add 1 day
      const exclusiveEnd = new Date(end);
      exclusiveEnd.setUTCDate(exclusiveEnd.getUTCDate() + 1);
      lines.push(`DTEND;VALUE=DATE:${toIcsDate(exclusiveEnd)}`);
    } else {
      // Single date — assume the day, full event
      lines.push(`DTSTART;VALUE=DATE:${toIcsDate(start)}`);
      lines.push(`DTEND;VALUE=DATE:${toIcsDate(start)}`);
    }

    lines.push(`SUMMARY:${escIcs(`Barry: ${trip.name}`)}`);

    const description = [
      `Organized by ${trip.organizer?.firstName || ''} ${trip.organizer?.lastName || ''}`.trim(),
      `${trip.participants.length} participant${trip.participants.length === 1 ? '' : 's'}`,
      `Mode: ${isTrip ? 'Multi-day trip' : 'Wanderlust outing'}`,
      ctx.totalCost ? `Total cost: ${ctx.totalCost.toFixed(0)} EUR` : '',
      '',
      'Generated by Barry — your group meetup planner.',
    ].filter(Boolean).join('\\n');
    lines.push(`DESCRIPTION:${description}`);

    if (trip.selectedVenueId) {
      lines.push(`LOCATION:${escIcs(trip.selectedVenueId)}`);
    }
    lines.push('END:VEVENT');
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

export function downloadIcs(ctx: ExportContext) {
  const ics = buildIcs(ctx);
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `barry-${ctx.trip.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ============================================================
// PDF EXPORT — opens print-friendly HTML in new tab
// User clicks print -> Save as PDF
// (Avoids adding jsPDF as a dep; native browser print is good enough for v1)
// ============================================================

const TRANSPORT_LABEL: Record<string, string> = {
  walk: 'Walking', bike: 'Cycling', transit: 'Public transit',
  car: 'Car', train: 'Train', flight: 'Flight',
};

export function buildPdfHtml(ctx: ExportContext): string {
  const { trip, reservations = [], transportLegs = [] } = ctx;
  const isTrip = trip.mode === 'trip';
  const dateLabel = (() => {
    if (!trip.scheduledAt) return 'Date pending';
    const start = new Date(trip.scheduledAt);
    const dStr = start.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' });
    if (isTrip && trip.endDate) {
      const end = new Date(trip.endDate);
      const eStr = end.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
      const nights = Math.max(1, Math.round((end.getTime() - start.getTime()) / 86400000));
      return `${dStr} → ${eStr} (${nights} night${nights === 1 ? '' : 's'})`;
    }
    return dStr;
  })();

  const totalCost = ctx.totalCost ?? (
    reservations.reduce((s, r) => s + r.amount, 0)
    + transportLegs.reduce((s, l) => s + (l.cost || 0), 0)
  );

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Barry recap: ${trip.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Helvetica Neue', system-ui, sans-serif;
      color: #1E293B;
      background: white;
      padding: 40px 32px;
      max-width: 720px;
      margin: 0 auto;
      line-height: 1.45;
    }
    h1 { font-size: 28px; margin-bottom: 4px; letter-spacing: -0.5px; }
    h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; color: #475569; text-transform: uppercase; letter-spacing: 1px; font-weight: 800; font-size: 11px; }
    .header { border-bottom: 3px solid #2563EB; padding-bottom: 16px; margin-bottom: 16px; }
    .meta { color: #64748B; font-size: 13px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; }
    .badge-blue { background: #DBEAFE; color: #1D4ED8; }
    .badge-violet { background: #EDE9FE; color: #6D28D9; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    table th { text-align: left; padding: 6px 4px; color: #64748B; font-weight: 600; font-size: 11px; text-transform: uppercase; }
    table td { padding: 6px 4px; border-top: 1px solid #E2E8F0; }
    .total { font-size: 18px; font-weight: 800; color: #2563EB; }
    .row { display: flex; justify-content: space-between; align-items: baseline; padding: 6px 0; border-bottom: 1px solid #F1F5F9; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <span class="badge ${isTrip ? 'badge-violet' : 'badge-blue'}">${isTrip ? 'Trip' : 'Wanderlust'}</span>
    <h1>${escapeHtml(trip.name)}</h1>
    <p class="meta">${escapeHtml(dateLabel)} · ${trip.participants.length} participant${trip.participants.length === 1 ? '' : 's'}</p>
  </div>

  <h2>Participants</h2>
  <table>
    <thead><tr><th>Name</th><th>Origin</th><th>Transport</th><th style="text-align:right">Budget</th></tr></thead>
    <tbody>
      ${trip.participants.map(p => `
        <tr>
          <td>${escapeHtml(`${p.user?.firstName || ''} ${p.user?.lastName || ''}`.trim()) || 'Guest'}</td>
          <td>${escapeHtml(p.originLabel || 'Not set')}</td>
          <td>${escapeHtml(TRANSPORT_LABEL[p.transportMode] || p.transportMode)}</td>
          <td style="text-align:right">${p.maxMoney ? p.maxMoney.toFixed(0) + ' EUR' : '—'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  ${transportLegs.length > 0 ? `
  <h2>Transport plan</h2>
  <table>
    <thead><tr><th>Person</th><th>Mode</th><th>From</th><th style="text-align:right">Cost</th></tr></thead>
    <tbody>
      ${transportLegs.map(leg => {
        const p = trip.participants.find(pp => pp.userId === leg.userId);
        return `
          <tr>
            <td>${escapeHtml(p?.user?.firstName || 'Guest')}</td>
            <td>${escapeHtml(TRANSPORT_LABEL[leg.mode] || leg.mode)}</td>
            <td>${escapeHtml(p?.originLabel?.split(',')[0] || '')}</td>
            <td style="text-align:right">${leg.cost ? leg.cost.toFixed(2) + ' EUR' : '—'}</td>
          </tr>
        `;
      }).join('')}
    </tbody>
  </table>
  ` : ''}

  ${reservations.length > 0 ? `
  <h2>Reservations</h2>
  <table>
    <thead><tr><th>Type</th><th>Description</th><th>Reference</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>
      ${reservations.map(r => `
        <tr>
          <td style="text-transform:capitalize">${escapeHtml(r.type)}</td>
          <td>${escapeHtml(r.description)}</td>
          <td><code style="font-size:11px;background:#F1F5F9;padding:1px 4px;border-radius:3px">${escapeHtml(r.confirmationCode || r.reference)}</code></td>
          <td style="text-align:right">${r.amount.toFixed(2)} EUR</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  ` : ''}

  <div style="margin-top:24px; padding:12px 0; border-top:2px solid #1E293B; display:flex; justify-content:space-between;">
    <span style="font-weight:700">Total</span>
    <span class="total">${totalCost.toFixed(2)} EUR</span>
  </div>

  <div class="footer">
    Generated by Barry on ${new Date().toLocaleDateString('en-GB')} · barry.app
  </div>

  <script>
    window.onload = () => setTimeout(() => window.print(), 300);
  </script>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return (s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function downloadPdf(ctx: ExportContext) {
  const html = buildPdfHtml(ctx);
  const w = window.open('', '_blank');
  if (!w) {
    alert('Please allow pop-ups to export your trip recap.');
    return;
  }
  w.document.write(html);
  w.document.close();
}
