// ============================================================
// TRIP EXPORT — PDF (browser print) + ICS calendar
// PDF design uses Barry's graphic DNA: blue/indigo gradient header,
// rounded cards with subtle shadows, Inter/Manrope-like typography,
// avatar discs with deterministic colors, mode badges, etc.
// ============================================================

import type { Trip, Reservation, TransportLeg } from '@barry/shared-types';

interface ExportContext {
  trip: Trip;
  reservations?: Reservation[];
  transportLegs?: TransportLeg[];
  totalCost?: number;
}

// ============================================================
// AVATAR COLOR (matches the in-app palette)
// ============================================================
const AVATAR_PALETTE = ['#2563EB', '#F97316', '#10B981', '#8B5CF6', '#EF4444', '#EC4899', '#06B6D4', '#F59E0B'];
function colorForUser(userId?: string | null, fallback?: string | null): string {
  const seed = userId || fallback || 'unknown';
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash) + seed.charCodeAt(i);
    hash |= 0;
  }
  return AVATAR_PALETTE[Math.abs(hash) % AVATAR_PALETTE.length];
}

// ============================================================
// ICS CALENDAR — RFC 5545
// ============================================================

function pad2(n: number) { return n < 10 ? `0${n}` : `${n}`; }

function toIcsDateTime(d: Date): string {
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}T${pad2(d.getUTCHours())}${pad2(d.getUTCMinutes())}${pad2(d.getUTCSeconds())}Z`;
}

function toIcsDate(d: Date): string {
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}`;
}

function escIcs(s: string): string {
  return (s || '').replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n').replace(/\r/g, '');
}

export function buildIcs(ctx: ExportContext): string {
  const { trip } = ctx;
  const now = toIcsDateTime(new Date());
  const isTrip = trip.mode === 'trip';
  const start = trip.scheduledAt ? new Date(trip.scheduledAt) : null;
  const end = trip.endDate ? new Date(trip.endDate) : null;

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Barry//Trip Export//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  if (start) {
    lines.push('BEGIN:VEVENT');
    lines.push(`UID:${trip.id}@barry.app`);
    lines.push(`DTSTAMP:${now}`);

    if (isTrip && end) {
      lines.push(`DTSTART;VALUE=DATE:${toIcsDate(start)}`);
      const exclusiveEnd = new Date(end);
      exclusiveEnd.setUTCDate(exclusiveEnd.getUTCDate() + 1);
      lines.push(`DTEND;VALUE=DATE:${toIcsDate(exclusiveEnd)}`);
    } else {
      lines.push(`DTSTART;VALUE=DATE:${toIcsDate(start)}`);
      lines.push(`DTEND;VALUE=DATE:${toIcsDate(start)}`);
    }

    lines.push(`SUMMARY:${escIcs(`Barry: ${trip.name}`)}`);

    const description = [
      `Organized by ${trip.organizer?.firstName || ''} ${trip.organizer?.lastName || ''}`.trim(),
      `${trip.participants.length} participant${trip.participants.length === 1 ? '' : 's'}`,
      `Mode: ${isTrip ? 'Multi-day trip' : 'Wanderlust outing'}`,
      ctx.totalCost ? `Total cost: ${ctx.totalCost.toFixed(0)} EUR` : '',
      '',
      'Generated by Barry, your group meetup planner.',
    ].filter(Boolean).join('\\n');
    lines.push(`DESCRIPTION:${description}`);

    if (trip.selectedVenueId) {
      lines.push(`LOCATION:${escIcs(trip.selectedVenueId)}`);
    }
    lines.push('END:VEVENT');
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

export function downloadIcs(ctx: ExportContext) {
  const ics = buildIcs(ctx);
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `barry-${ctx.trip.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ============================================================
// PDF EXPORT — Barry-branded HTML, opens print-friendly in new tab
// ============================================================

const TRANSPORT_LABEL: Record<string, string> = {
  walk: 'Walking', bike: 'Cycling', transit: 'Public transit',
  car: 'Car', train: 'Train', flight: 'Flight',
};

function escHtml(s: string): string {
  return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function avatarSvg(user: any, size = 28): string {
  const firstInitial = (user?.firstName?.[0] || '?').toUpperCase();
  const lastInitial = (user?.lastName?.[0] || '').toUpperCase();
  const initials = (firstInitial + lastInitial).slice(0, 2);
  const color = colorForUser(user?.id, user?.firstName);
  const fontSize = Math.round(size * 0.36);
  return `<span style="display:inline-flex;align-items:center;justify-content:center;width:${size}px;height:${size}px;border-radius:50%;background:${color};color:white;font-weight:700;font-size:${fontSize}px;flex-shrink:0;letter-spacing:-0.5px;">${escHtml(initials)}</span>`;
}

export function buildPdfHtml(ctx: ExportContext): string {
  const { trip, reservations = [], transportLegs = [] } = ctx;
  const isTrip = trip.mode === 'trip';

  const dateLabel = (() => {
    if (!trip.scheduledAt) return 'Date pending';
    const start = new Date(trip.scheduledAt);
    const dStr = start.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
    if (isTrip && trip.endDate) {
      const end = new Date(trip.endDate);
      const eStr = end.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' });
      const nights = Math.max(1, Math.round((end.getTime() - start.getTime()) / 86400000));
      return `${dStr} → ${eStr} <span style="color:#94A3B8;font-weight:500;">· ${nights} night${nights === 1 ? '' : 's'}</span>`;
    }
    return dStr;
  })();

  const totalCost = ctx.totalCost ?? (
    reservations.reduce((s, r) => s + r.amount, 0)
    + transportLegs.reduce((s, l) => s + (l.cost || 0), 0)
  );

  const transportTotal = transportLegs.reduce((s, l) => s + (l.cost || 0), 0);
  const reservationTotal = reservations.reduce((s, r) => s + r.amount, 0);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Barry recap: ${escHtml(trip.name)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    @page { size: A4; margin: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Inter', 'Manrope', system-ui, sans-serif;
      color: #0F172A;
      background: #F8FAFC;
      line-height: 1.5;
      -webkit-font-smoothing: antialiased;
    }
    .page {
      max-width: 720px;
      margin: 0 auto;
      background: white;
      min-height: 100vh;
      padding: 0;
    }

    /* HERO — Barry blue gradient */
    .hero {
      background: linear-gradient(135deg, #2563EB 0%, #1D4ED8 60%, #4F46E5 100%);
      color: white;
      padding: 32px 32px 28px;
      position: relative;
      overflow: hidden;
    }
    .hero::before {
      content: '';
      position: absolute;
      top: -60px; right: -60px;
      width: 200px; height: 200px;
      background: rgba(255,255,255,0.08);
      border-radius: 50%;
    }
    .hero::after {
      content: '';
      position: absolute;
      bottom: -40px; left: -40px;
      width: 140px; height: 140px;
      background: rgba(255,255,255,0.05);
      border-radius: 50%;
    }
    .hero-row { display: flex; justify-content: space-between; align-items: flex-start; position: relative; z-index: 1; margin-bottom: 18px; }
    .brand { display: flex; align-items: center; gap: 8px; }
    .brand-mark {
      width: 32px; height: 32px;
      background: white;
      border-radius: 8px;
      display: flex; align-items: center; justify-content: center;
      color: #2563EB;
      font-weight: 900;
      font-size: 18px;
      letter-spacing: -1px;
    }
    .brand-name { font-size: 18px; font-weight: 800; letter-spacing: -0.5px; }
    .mode-pill {
      background: rgba(255,255,255,0.15);
      backdrop-filter: blur(8px);
      padding: 4px 10px;
      border-radius: 999px;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      border: 1px solid rgba(255,255,255,0.2);
    }
    .hero-title {
      font-size: 32px;
      font-weight: 800;
      letter-spacing: -1px;
      line-height: 1.1;
      margin-bottom: 6px;
      position: relative;
      z-index: 1;
    }
    .hero-meta {
      font-size: 14px;
      color: rgba(255,255,255,0.85);
      position: relative;
      z-index: 1;
    }
    .hero-stats {
      display: flex;
      gap: 24px;
      margin-top: 20px;
      position: relative;
      z-index: 1;
    }
    .hero-stat {
      flex: 1;
      background: rgba(255,255,255,0.1);
      backdrop-filter: blur(8px);
      border: 1px solid rgba(255,255,255,0.15);
      padding: 10px 14px;
      border-radius: 12px;
    }
    .hero-stat-label { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; color: rgba(255,255,255,0.7); }
    .hero-stat-value { font-size: 18px; font-weight: 800; margin-top: 2px; letter-spacing: -0.3px; }

    /* CONTENT */
    .content { padding: 28px 32px 40px; }
    .section { margin-bottom: 24px; }
    .section-title {
      font-size: 10px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: #64748B;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .section-title::before {
      content: '';
      width: 4px;
      height: 14px;
      background: #2563EB;
      border-radius: 2px;
      display: inline-block;
    }

    /* PARTICIPANT CARDS */
    .participants {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: 8px;
    }
    .participant-card {
      display: flex;
      align-items: center;
      gap: 10px;
      background: #F8FAFC;
      border: 1px solid #E2E8F0;
      border-radius: 12px;
      padding: 10px 12px;
    }
    .participant-info { flex: 1; min-width: 0; }
    .participant-name { font-size: 13px; font-weight: 700; color: #0F172A; }
    .participant-meta { font-size: 11px; color: #64748B; margin-top: 1px; }

    /* TRANSPORT TABLE */
    .transport-row {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 10px 12px;
      border-bottom: 1px solid #F1F5F9;
    }
    .transport-row:last-child { border-bottom: none; }
    .transport-mode-pill {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 10px;
      font-weight: 700;
      background: #EEF2FF;
      color: #4338CA;
    }
    .transport-cost {
      font-weight: 700;
      color: #0F172A;
      font-size: 13px;
    }

    /* RESERVATION CARDS */
    .reservation {
      background: #F0FDF4;
      border: 1px solid #BBF7D0;
      border-radius: 12px;
      padding: 12px 14px;
      margin-bottom: 8px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .reservation-icon {
      width: 36px; height: 36px;
      background: #10B981;
      border-radius: 8px;
      display: flex; align-items: center; justify-content: center;
      color: white;
      flex-shrink: 0;
    }
    .reservation-content { flex: 1; min-width: 0; }
    .reservation-type {
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #047857;
      font-weight: 700;
    }
    .reservation-desc { font-size: 13px; font-weight: 600; color: #0F172A; }
    .reservation-code {
      font-family: 'JetBrains Mono', 'Courier New', monospace;
      font-size: 11px;
      background: white;
      border: 1px solid #BBF7D0;
      padding: 1px 6px;
      border-radius: 4px;
      color: #065F46;
      margin-top: 2px;
      display: inline-block;
    }
    .reservation-amount {
      font-size: 14px;
      font-weight: 800;
      color: #047857;
      flex-shrink: 0;
    }

    /* TOTAL */
    .total-card {
      background: linear-gradient(135deg, #2563EB 0%, #4F46E5 100%);
      color: white;
      padding: 20px 24px;
      border-radius: 16px;
      margin-top: 24px;
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      box-shadow: 0 10px 25px -5px rgba(37,99,235,0.25);
    }
    .total-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      font-weight: 700;
      opacity: 0.85;
    }
    .total-value {
      font-size: 32px;
      font-weight: 900;
      letter-spacing: -1px;
    }

    /* FOOTER */
    .footer {
      padding: 20px 32px;
      border-top: 1px solid #E2E8F0;
      background: #F8FAFC;
      text-align: center;
    }
    .footer-tagline {
      font-size: 11px;
      color: #94A3B8;
    }
    .footer-tagline strong { color: #2563EB; font-weight: 800; }

    /* PRINT */
    @media print {
      body { background: white; }
      .page { box-shadow: none; }
      .hero { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .total-card { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .reservation-icon { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div class="page">
    <!-- HERO with Barry brand -->
    <div class="hero">
      <div class="hero-row">
        <div class="brand">
          <div class="brand-mark">B</div>
          <div class="brand-name">Barry</div>
        </div>
        <div class="mode-pill">${isTrip ? 'Trip' : 'Wanderlust'}</div>
      </div>
      <h1 class="hero-title">${escHtml(trip.name)}</h1>
      <p class="hero-meta">${dateLabel}</p>
      <div class="hero-stats">
        <div class="hero-stat">
          <div class="hero-stat-label">Crew</div>
          <div class="hero-stat-value">${trip.participants.length}</div>
        </div>
        <div class="hero-stat">
          <div class="hero-stat-label">Transport</div>
          <div class="hero-stat-value">${transportTotal.toFixed(0)} EUR</div>
        </div>
        <div class="hero-stat">
          <div class="hero-stat-label">Bookings</div>
          <div class="hero-stat-value">${reservationTotal.toFixed(0)} EUR</div>
        </div>
      </div>
    </div>

    <!-- BODY -->
    <div class="content">

      <!-- Crew -->
      <section class="section">
        <h2 class="section-title">The crew</h2>
        <div class="participants">
          ${trip.participants.map(p => `
            <div class="participant-card">
              ${avatarSvg(p.user || { firstName: 'Guest' }, 32)}
              <div class="participant-info">
                <div class="participant-name">${escHtml(`${p.user?.firstName || ''} ${p.user?.lastName || ''}`.trim()) || 'Guest'}</div>
                <div class="participant-meta">${escHtml(TRANSPORT_LABEL[p.transportMode] || p.transportMode)}${p.maxMoney ? ' · max ' + p.maxMoney + ' EUR' : ''}</div>
              </div>
            </div>
          `).join('')}
        </div>
      </section>

      ${transportLegs.length > 0 ? `
      <!-- Transport -->
      <section class="section">
        <h2 class="section-title">Transport plan</h2>
        <div style="background:white;border:1px solid #E2E8F0;border-radius:12px;overflow:hidden;">
          ${transportLegs.map(leg => {
            const p = trip.participants.find(pp => pp.userId === leg.userId);
            return `
              <div class="transport-row">
                ${avatarSvg(p?.user || { firstName: 'G' }, 24)}
                <div style="flex:1;min-width:0;">
                  <div style="font-size:13px;font-weight:700;">${escHtml(p?.user?.firstName || 'Guest')}</div>
                  <div style="font-size:11px;color:#64748B;margin-top:1px;">
                    ${escHtml(p?.originLabel?.split(',')[0] || 'Origin TBD')}
                    ${leg.duration ? ` · ${Math.round(leg.duration / 60)} min` : ''}
                  </div>
                </div>
                <span class="transport-mode-pill">${escHtml(TRANSPORT_LABEL[leg.mode] || leg.mode)}</span>
                ${leg.cost ? `<span class="transport-cost">${leg.cost.toFixed(0)} EUR</span>` : ''}
              </div>
            `;
          }).join('')}
        </div>
      </section>
      ` : ''}

      ${reservations.length > 0 ? `
      <!-- Reservations -->
      <section class="section">
        <h2 class="section-title">Confirmed bookings</h2>
        ${reservations.map(r => {
          const icon = r.type === 'venue' ?
            '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.2" stroke-linecap="round"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>' :
            r.type === 'accommodation' ?
            '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.2" stroke-linecap="round"><path d="M3 21V8l9-4 9 4v13"/><path d="M9 21v-8h6v8"/></svg>' :
            '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.2" stroke-linecap="round"><path d="M16 3h5v5"/><path d="M4 20L21 3"/><path d="M21 16v5h-5"/><path d="M15 15l6 6"/><path d="M4 4l5 5"/></svg>';
          return `
            <div class="reservation">
              <div class="reservation-icon">${icon}</div>
              <div class="reservation-content">
                <div class="reservation-type">${escHtml(r.type)}</div>
                <div class="reservation-desc">${escHtml(r.description)}</div>
                <div class="reservation-code">${escHtml(r.confirmationCode || r.reference)}</div>
              </div>
              <div class="reservation-amount">${r.amount.toFixed(0)} EUR</div>
            </div>
          `;
        }).join('')}
      </section>
      ` : ''}

      <!-- Total -->
      <div class="total-card">
        <span class="total-label">Total trip cost</span>
        <span class="total-value">${totalCost.toFixed(0)} EUR</span>
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <p class="footer-tagline">
        Made with care by <strong>Barry</strong> · Where the smart group meets · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
      </p>
    </div>
  </div>

  <script>
    window.onload = () => setTimeout(() => window.print(), 400);
  </script>
</body>
</html>`;
}

export function downloadPdf(ctx: ExportContext) {
  const html = buildPdfHtml(ctx);
  const w = window.open('', '_blank');
  if (!w) {
    alert('Please allow pop-ups to export your trip recap.');
    return;
  }
  w.document.write(html);
  w.document.close();
}
